# Task 2 : Some basic SQL Operations will be performed on the cleaned dataset

In [1]:
!pip install sqlalchemy -q

1. Importing cleaned dataset

In [2]:
import pandas as pd

df = pd.read_csv("/content/online_retail_cleaned.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)
df.head()

Dataset loaded successfully!
Shape: (296607, 9)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,SalesAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

2. Creating sqlite database

In [3]:
import sqlite3

conn = sqlite3.connect("/content/online_retail.db")

df.to_sql(
    "online_retail",
    conn,
    if_exists="replace",
    index=False
)

print("SQLite database created successfully!")

SQLite database created successfully!

3. Running first Query

In [4]:
query = """
SELECT *
FROM online_retail
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)

result

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,SalesAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2.0,2010-12-01 08:26:00,7.65,17850.0,United Kingdom,15.30
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6.0,2010-12-01 08:26:00,4.25,17850.0,United Kingdom,25.50
7,536366,22633,HAND WARMER UNION JACK,6.0,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,11.10
8,536366,22632,HAND WARMER RED POLKA DOT,6.0,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,11.10
9,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6.0,2010-12-01 08:34:00,2.10,13047.0,United Kingdom,12.60

In [5]:
query = """
PRAGMA table_info(online_retail);
"""

pd.read_sql_query(query, conn)

   cid         name     type  notnull dflt_value  pk
0    0    InvoiceNo  INTEGER        0       None   0
1    1    StockCode     TEXT        0       None   0
2    2  Description     TEXT        0       None   0
3    3     Quantity     REAL        0       None   0
4    4  InvoiceDate     TEXT        0       None   0
5    5    UnitPrice     REAL        0       None   0
6    6   CustomerID     REAL        0       None   0
7    7      Country     TEXT        0       None   0
8    8  SalesAmount     REAL        0       None   0

Aggregation

In [6]:
query = """
SELECT
    SUM(SalesAmount) AS TotalSales
FROM online_retail;
"""

pd.read_sql_query(query, conn)

    TotalSales
0  3157350.822

In [7]:
query = """
SELECT
    COUNT(DISTINCT InvoiceNo) AS TotalOrders
FROM online_retail;
"""

pd.read_sql_query(query, conn)

   TotalOrders
0        11764

1.1. Select Clause

In [8]:
query = """
SELECT InvoiceNo, Description, Quantity, UnitPrice, SalesAmount
FROM online_retail
LIMIT 10;
"""

pd.read_sql_query(query, conn)

,InvoiceNo,Description,Quantity,UnitPrice,SalesAmount
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6.0,2.55,15.30
1,536365,WHITE METAL LANTERN,6.0,3.39,20.34
2,536365,CREAM CUPID HEARTS COAT HANGER,8.0,2.75,22.00
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,3.39,20.34
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6.0,3.39,20.34
5,536365,SET 7 BABUSHKA NESTING BOXES,2.0,7.65,15.30
6,536365,GLASS STAR FROSTED T-LIGHT HOLDER,6.0,4.25,25.50
7,536366,HAND WARMER UNION JACK,6.0,1.85,11.10
8,536366,HAND WARMER RED POLKA DOT,6.0,1.85,11.10
9,536367,POPPY'S PLAYHOUSE BEDROOM,6.0,2.10,12.60

1.2. Where Clause

In [9]:
query = """
SELECT InvoiceNo, Description, Quantity, SalesAmount
FROM online_retail
WHERE Quantity > 100
LIMIT 20;
"""

pd.read_sql_query(query, conn)

    InvoiceNo                        Description  Quantity  SalesAmount
0      536390    DISCO BALL CHRISTMAS DECORATION     288.0        28.80
1      537362                BROCADE RING PURSE      144.0        30.24
2      537852    DISCO BALL CHRISTMAS DECORATION     144.0        17.28
3      538356    DISCO BALL CHRISTMAS DECORATION     288.0        28.80
4      538367              MINI HIGHLIGHTER PENS     120.0        14.40
5      539041              ASSORTED INCENSE PACK     144.0        30.24
6      539307                   HEARTS GIFT TAPE     120.0        22.80
7      539307                 RED RETROSPOT TAPE     120.0        22.80
8      539307                        SKULLS TAPE     192.0        36.48
9      539307                     CUTE CATS TAPE     144.0        27.36
10     539307          CAKES AND BOWS GIFT  TAPE     144.0        27.36
11     539307       PENS ASSORTED FUNKY JEWELED      180.0        37.80
12     539307           PENS ASSORTED FUNNY FACE     180.0        37.80
13     539407      FELT FARM ANIMAL WHITE BUNNY      192.0        36.48
14     539586           PENS ASSORTED FUNNY FACE     108.0        22.68
15     539586            PENS ASSORTED SPACEBALL     108.0        22.68
16     539586       PENS ASSORTED FUNKY JEWELED      108.0        22.68
17     539586    MINI PAINTED GARDEN DECORATION      144.0        30.24
18     539628              MINI HIGHLIGHTER PENS     120.0        14.40
19     540025  SMALLFOLKART BAUBLE CHRISTMAS DEC     192.0        36.48

1.3. Order By Clause

In [10]:
query = """
SELECT InvoiceNo, Description, Quantity, SalesAmount
FROM online_retail
ORDER BY SalesAmount DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

   InvoiceNo                         Description  Quantity  SalesAmount
0     536860  3 HEARTS HANGING DECORATION RUSTIC      13.0        38.35
1     538168     PAPER CHAIN KIT 50'S CHRISTMAS       13.0        38.35
2     538626  WHITE HANGING HEART T-LIGHT HOLDER      13.0        38.35
3     539437          FAWN BLUE HOT WATER BOTTLE      13.0        38.35
4     539826  WHITE HANGING HEART T-LIGHT HOLDER      13.0        38.35
5     543040            PAPER BUNTING WHITE LACE      13.0        38.35
6     544586                FELTCRAFT DOLL MARIA      13.0        38.35
7     545215         WOODEN FRAME ANTIQUE WHITE       13.0        38.35
8     546377              PAPER CHAIN KIT EMPIRE      13.0        38.35
9     548203       FRENCH BLUE METAL DOOR SIGN 4      13.0        38.35

1.4. DISTINCT Clause

In [11]:
query = """
SELECT DISTINCT Country
FROM online_retail
ORDER BY Country;
"""

pd.read_sql_query(query, conn)

                 Country
0                   None
1              Australia
2                Austria
3                Bahrain
4                Belgium
5                 Brazil
6                 Canada
7        Channel Islands
8                 Cyprus
9         Czech Republic
10               Denmark
11                  EIRE
12    European Community
13               Finland
14                France
15               Germany
16                Greece
17             Hong Kong
18               Iceland
19                Israel
20                 Italy
21                 Japan
22               Lebanon
23             Lithuania
24                 Malta
25           Netherlands
26                Norway
27                Poland
28              Portugal
29          Saudi Arabia
30             Singapore
31                 Spain
32                Sweden
33           Switzerland
34                   USA
35  United Arab Emirates
36        United Kingdom
37           Unspecified

1.5. COUNT Clause

In [12]:
query = """
SELECT COUNT(*) AS TotalTransactions
FROM online_retail;
"""

pd.read_sql_query(query, conn)

   TotalTransactions
0             296607

1.6. GROUP BY Clause

In [13]:
query = """
SELECT
    Country,
    SUM(SalesAmount) AS TotalSales
FROM online_retail
GROUP BY Country
ORDER BY TotalSales DESC;
"""

pd.read_sql_query(query, conn)

                 Country   TotalSales
0         United Kingdom  2777079.642
1                Germany    84712.540
2                 France    73956.610
3                   EIRE    66950.330
4                  Spain    20741.180
5                Belgium    20049.190
6            Switzerland    16364.890
7               Portugal    11019.690
8                 Norway     8326.490
9        Channel Islands     7876.430
10           Netherlands     7650.040
11                 Italy     6858.460
12               Finland     6544.390
13             Australia     6413.750
14                Cyprus     4577.590
15                Poland     4210.950
16               Austria     3832.940
17                Israel     3688.950
18           Unspecified     3591.470
19                Sweden     3054.410
20             Hong Kong     3044.970
21               Denmark     2810.610
22                Canada     2208.720
23               Iceland     2118.560
24             Singapore     1737.080
25                 Malta     1533.910
26                Greece     1215.390
27  United Arab Emirates     1148.680
28    European Community     1012.250
29                 Japan      857.410
30               Lebanon      583.130
31                Brazil      416.340
32                   USA      307.450
33               Bahrain      274.000
34             Lithuania      233.100
35        Czech Republic      203.360
36          Saudi Arabia      145.920
37                  None          NaN

1.7. HAVING Clause

In [14]:
query = """
SELECT
    Country,
    SUM(SalesAmount) AS TotalSales
FROM online_retail
GROUP BY Country
HAVING SUM(SalesAmount) > 10000
ORDER BY TotalSales DESC;
"""

pd.read_sql_query(query, conn)

          Country   TotalSales
0  United Kingdom  2777079.642
1         Germany    84712.540
2          France    73956.610
3            EIRE    66950.330
4           Spain    20741.180
5         Belgium    20049.190
6     Switzerland    16364.890
7        Portugal    11019.690

1.8. Multiple Aggregate Functions

In [15]:
query = """
SELECT
    COUNT(DISTINCT InvoiceNo) AS TotalOrders,
    COUNT(DISTINCT StockCode) AS UniqueProducts,
    SUM(Quantity) AS TotalQuantity,
    SUM(SalesAmount) AS TotalSales,
    AVG(SalesAmount) AS AverageTransactionValue,
    MIN(SalesAmount) AS MinimumSale,
    MAX(SalesAmount) AS MaximumSale
FROM online_retail;
"""

pd.read_sql_query(query, conn)

,TotalOrders,UniqueProducts,TotalQuantity,TotalSales,AverageTransactionValue,MinimumSale,MaximumSale
0,11764,3650,1844208.0,3157350.822,10.644932,0.001,38.35

Sales by Product

In [16]:
query = """
SELECT
    Description,
    SUM(Quantity) AS TotalQuantity,
    SUM(SalesAmount) AS TotalSales
FROM online_retail
GROUP BY Description
ORDER BY TotalSales DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

                          Description  TotalQuantity  TotalSales
0  WHITE HANGING HEART T-LIGHT HOLDER         7251.0    22242.73
1            REGENCY CAKESTAND 3 TIER         1364.0    18229.11
2             JUMBO BAG RED RETROSPOT         6612.0    15424.77
3                       PARTY BUNTING         2727.0    14807.16
4     NATURAL SLATE HEART CHALKBOARD          4071.0    13019.13
5             LUNCH BAG RED RETROSPOT         7326.0    12940.86
6   SET OF 3 CAKE TINS PANTRY DESIGN          2342.0    12567.20
7       ASSORTED COLOUR BIRD ORNAMENT         7198.0    12429.58
8            JAM MAKING SET WITH JARS         2592.0    11986.64
9                      SPOTTY BUNTING         2148.0    11099.80

Sales by Month

In [17]:
query = """
SELECT
    strftime('%Y-%m', InvoiceDate) AS YearMonth,
    SUM(SalesAmount) AS TotalSales
FROM online_retail
GROUP BY YearMonth
ORDER BY YearMonth;
"""

pd.read_sql_query(query, conn)

   YearMonth  TotalSales
0       None         NaN
1    2010-12  382882.640
2    2011-01  311149.480
3    2011-02  267715.360
4    2011-03  348730.100
5    2011-04  288216.921
6    2011-05  376194.110
7    2011-06  347813.370
8    2011-07  352784.951
9    2011-08  351002.740
10   2011-09  130861.150

In [19]:
query = """
SELECT
    InvoiceNo,
    Description,
    Quantity,
    SalesAmount
FROM online_retail
WHERE SalesAmount > (
    SELECT AVG(SalesAmount)
    FROM online_retail
)
ORDER BY SalesAmount DESC
LIMIT 20;
"""

pd.read_sql_query(query, conn)

    InvoiceNo                          Description  Quantity  SalesAmount
0      536860   3 HEARTS HANGING DECORATION RUSTIC      13.0        38.35
1      538168      PAPER CHAIN KIT 50'S CHRISTMAS       13.0        38.35
2      538626   WHITE HANGING HEART T-LIGHT HOLDER      13.0        38.35
3      539437           FAWN BLUE HOT WATER BOTTLE      13.0        38.35
4      539826   WHITE HANGING HEART T-LIGHT HOLDER      13.0        38.35
5      543040             PAPER BUNTING WHITE LACE      13.0        38.35
6      544586                 FELTCRAFT DOLL MARIA      13.0        38.35
7      545215          WOODEN FRAME ANTIQUE WHITE       13.0        38.35
8      546377               PAPER CHAIN KIT EMPIRE      13.0        38.35
9      548203        FRENCH BLUE METAL DOOR SIGN 4      13.0        38.35
10     548203            FRENCH WC SIGN BLUE METAL      13.0        38.35
11     548712    RECIPE BOX BLUE SKETCHBOOK DESIGN      13.0        38.35
12     549320   WHITE HANGING HEART T-LIGHT HOLDER      13.0        38.35
13     550301            CALENDAR PAPER CUT DESIGN      13.0        38.35
14     551468   WHITE HANGING HEART T-LIGHT HOLDER      13.0        38.35
15     539958               ACRYLIC GEOMETRIC LAMP       1.0        38.26
16     536592  DIAMANTE HEART SHAPED WALL MIRROR,        3.0        38.25
17     536681             REGENCY CAKESTAND 3 TIER       3.0        38.25
18     536947             REGENCY CAKESTAND 3 TIER       3.0        38.25
19     537159           VICTORIAN SEWING BOX LARGE       3.0        38.25

CTE : Common Table Expression

In [20]:
query = """
WITH CountrySales AS (
    SELECT
        Country,
        SUM(SalesAmount) AS TotalSales
    FROM online_retail
    GROUP BY Country
)
SELECT
    Country,
    TotalSales
FROM CountrySales
WHERE TotalSales > 10000
ORDER BY TotalSales DESC;
"""

pd.read_sql_query(query, conn)

          Country   TotalSales
0  United Kingdom  2777079.642
1         Germany    84712.540
2          France    73956.610
3            EIRE    66950.330
4           Spain    20741.180
5         Belgium    20049.190
6     Switzerland    16364.890
7        Portugal    11019.690

Window Function

In [21]:
query = """
WITH CountrySales AS (
    SELECT
        Country,
        SUM(SalesAmount) AS TotalSales
    FROM online_retail
    GROUP BY Country
)
SELECT
    Country,
    TotalSales,
    RANK() OVER (ORDER BY TotalSales DESC) AS SalesRank
FROM CountrySales
ORDER BY SalesRank;
"""

pd.read_sql_query(query, conn)

                 Country   TotalSales  SalesRank
0         United Kingdom  2777079.642          1
1                Germany    84712.540          2
2                 France    73956.610          3
3                   EIRE    66950.330          4
4                  Spain    20741.180          5
5                Belgium    20049.190          6
6            Switzerland    16364.890          7
7               Portugal    11019.690          8
8                 Norway     8326.490          9
9        Channel Islands     7876.430         10
10           Netherlands     7650.040         11
11                 Italy     6858.460         12
12               Finland     6544.390         13
13             Australia     6413.750         14
14                Cyprus     4577.590         15
15                Poland     4210.950         16
16               Austria     3832.940         17
17                Israel     3688.950         18
18           Unspecified     3591.470         19
19                Sweden     3054.410         20
20             Hong Kong     3044.970         21
21               Denmark     2810.610         22
22                Canada     2208.720         23
23               Iceland     2118.560         24
24             Singapore     1737.080         25
25                 Malta     1533.910         26
26                Greece     1215.390         27
27  United Arab Emirates     1148.680         28
28    European Community     1012.250         29
29                 Japan      857.410         30
30               Lebanon      583.130         31
31                Brazil      416.340         32
32                   USA      307.450         33
33               Bahrain      274.000         34
34             Lithuania      233.100         35
35        Czech Republic      203.360         36
36          Saudi Arabia      145.920         37
37                  None          NaN         38

Window Function - Product Ranking

In [22]:
query = """
WITH ProductSales AS (
    SELECT
        Description,
        SUM(SalesAmount) AS TotalSales
    FROM online_retail
    GROUP BY Description
)
SELECT
    Description,
    TotalSales,
    RANK() OVER (ORDER BY TotalSales DESC) AS SalesRank
FROM ProductSales
ORDER BY SalesRank
LIMIT 20;
"""

pd.read_sql_query(query, conn)

                           Description  TotalSales  SalesRank
0   WHITE HANGING HEART T-LIGHT HOLDER    22242.73          1
1             REGENCY CAKESTAND 3 TIER    18229.11          2
2              JUMBO BAG RED RETROSPOT    15424.77          3
3                        PARTY BUNTING    14807.16          4
4      NATURAL SLATE HEART CHALKBOARD     13019.13          5
5              LUNCH BAG RED RETROSPOT    12940.86          6
6    SET OF 3 CAKE TINS PANTRY DESIGN     12567.20          7
7        ASSORTED COLOUR BIRD ORNAMENT    12429.58          8
8             JAM MAKING SET WITH JARS    11986.64          9
9                       SPOTTY BUNTING    11099.80         10
10              JAM MAKING SET PRINTED    10767.44         11
11    ROSES REGENCY TEACUP AND SAUCER     10188.92         12
12              JUMBO STORAGE BAG SUKI     9881.35         13
13             JUMBO BAG PINK POLKADOT     9861.33         14
14     GREEN REGENCY TEACUP AND SAUCER     9811.20         15
15                 LUNCH BAG CARS BLUE     9680.31         16
16   JUMBO SHOPPER VINTAGE RED PAISLEY     9559.48         17
17             LUNCH BAG  BLACK SKULL.     9431.20         18
18     VICTORIAN GLASS HANGING T-LIGHT     9361.89         19
19             LUNCH BAG PINK POLKADOT     9274.15         20

View

In [23]:
query = """
CREATE VIEW IF NOT EXISTS country_sales AS
SELECT
    Country,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders,
    SUM(Quantity) AS TotalQuantity,
    SUM(SalesAmount) AS TotalSales
FROM online_retail
GROUP BY Country;
"""

conn.execute(query)
conn.commit()

print("View created successfully!")

View created successfully!

Retrieving the View

In [24]:
query = """
SELECT *
FROM country_sales
ORDER BY TotalSales DESC;
"""

pd.read_sql_query(query, conn)

                 Country  TotalOrders  TotalQuantity   TotalSales
0         United Kingdom        10649      1596164.0  2777079.642
1                Germany          274        55767.0    84712.540
2                 France          232        47670.0    73956.610
3                   EIRE          157        42380.0    66950.330
4                  Spain           55        11843.0    20741.180
5                Belgium           67        12939.0    20049.190
6            Switzerland           30        10866.0    16364.890
7               Portugal           28         7068.0    11019.690
8                 Norway           15         6267.0     8326.490
9        Channel Islands           12         4146.0     7876.430
10           Netherlands           41         8385.0     7650.040
11                 Italy           19         3658.0     6858.460
12               Finland           19         4798.0     6544.390
13             Australia           34         4104.0     6413.750
14                Cyprus            9         2245.0     4577.590
15                Poland           16         2223.0     4210.950
16               Austria           13         2364.0     3832.940
17                Israel            6         2727.0     3688.950
18           Unspecified           11         2594.0     3591.470
19                Sweden           19         1913.0     3054.410
20             Hong Kong            5         2006.0     3044.970
21               Denmark            8         2161.0     2810.610
22                Canada            4         1798.0     2208.720
23               Iceland            5         1236.0     2118.560
24             Singapore            3         1576.0     1737.080
25                 Malta            4          752.0     1533.910
26                Greece            4          795.0     1215.390
27  United Arab Emirates            2          759.0     1148.680
28    European Community            3          456.0     1012.250
29                 Japan            9         1528.0      857.410
30               Lebanon            1          237.0      583.130
31                Brazil            1          170.0      416.340
32                   USA            1          131.0      307.450
33               Bahrain            2           92.0      274.000
34             Lithuania            3          110.0      233.100
35        Czech Republic            1          200.0      203.360
36          Saudi Arabia            1           80.0      145.920
37                  None            1            NaN          NaN

In [25]:
query = """
SELECT name
FROM sqlite_master
WHERE type = 'view';
"""

pd.read_sql_query(query, conn)

            name
0  country_sales

# Answer of 10 Business Questions

1. What is the total Revenue

In [26]:
query = """
SELECT
    ROUND(SUM(SalesAmount), 2) AS TotalRevenue
FROM online_retail;
"""

pd.read_sql_query(query, conn)

   TotalRevenue
0    3157350.82

2. Which are the top 10 products by Revenue

In [27]:
query = """
SELECT
    Description,
    ROUND(SUM(SalesAmount), 2) AS TotalRevenue
FROM online_retail
GROUP BY Description
ORDER BY TotalRevenue DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

                          Description  TotalRevenue
0  WHITE HANGING HEART T-LIGHT HOLDER      22242.73
1            REGENCY CAKESTAND 3 TIER      18229.11
2             JUMBO BAG RED RETROSPOT      15424.77
3                       PARTY BUNTING      14807.16
4     NATURAL SLATE HEART CHALKBOARD       13019.13
5             LUNCH BAG RED RETROSPOT      12940.86
6   SET OF 3 CAKE TINS PANTRY DESIGN       12567.20
7       ASSORTED COLOUR BIRD ORNAMENT      12429.58
8            JAM MAKING SET WITH JARS      11986.64
9                      SPOTTY BUNTING      11099.80

3. Which Countries generate most Revenue

In [28]:
query = """
SELECT
    Country,
    ROUND(SUM(SalesAmount), 2) AS TotalRevenue
FROM online_retail
GROUP BY Country
ORDER BY TotalRevenue DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

           Country  TotalRevenue
0   United Kingdom    2777079.64
1          Germany      84712.54
2           France      73956.61
3             EIRE      66950.33
4            Spain      20741.18
5          Belgium      20049.19
6      Switzerland      16364.89
7         Portugal      11019.69
8           Norway       8326.49
9  Channel Islands       7876.43

4. Which countries have most orders

In [29]:
query = """
SELECT
    Country,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders
FROM online_retail
GROUP BY Country
ORDER BY TotalOrders DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

          Country  TotalOrders
0  United Kingdom        10649
1         Germany          274
2          France          232
3            EIRE          157
4         Belgium           67
5           Spain           55
6     Netherlands           41
7       Australia           34
8     Switzerland           30
9        Portugal           28

5. What are the top 10 customers by revenue

In [30]:
query = """
SELECT
    CustomerID,
    ROUND(SUM(SalesAmount), 2) AS TotalRevenue
FROM online_retail
WHERE CustomerID IS NOT NULL
GROUP BY CustomerID
ORDER BY TotalRevenue DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

   CustomerID  TotalRevenue
0     14911.0      43958.74
1     13089.0      21071.96
2     17841.0      19709.80
3     14298.0      19615.81
4     15039.0      11907.95
5     13081.0      11412.60
6     14156.0      11237.27
7     12748.0      10716.07
8     17735.0      10103.33
9     15311.0       9481.58

6. What is monthly revenue trend?

In [31]:
query = """
SELECT
    strftime('%Y-%m', InvoiceDate) AS YearMonth,
    ROUND(SUM(SalesAmount), 2) AS MonthlyRevenue
FROM online_retail
GROUP BY YearMonth
ORDER BY YearMonth;
"""

pd.read_sql_query(query, conn)

   YearMonth  MonthlyRevenue
0       None             NaN
1    2010-12       382882.64
2    2011-01       311149.48
3    2011-02       267715.36
4    2011-03       348730.10
5    2011-04       288216.92
6    2011-05       376194.11
7    2011-06       347813.37
8    2011-07       352784.95
9    2011-08       351002.74
10   2011-09       130861.15

7. Which products ave the highest quantity sold?

In [32]:
query = """
SELECT
    Description,
    SUM(Quantity) AS TotalQuantitySold
FROM online_retail
GROUP BY Description
ORDER BY TotalQuantitySold DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

                           Description  TotalQuantitySold
0    WORLD WAR 2 GLIDERS ASSTD DESIGNS            13186.0
1      PACK OF 72 RETROSPOT CAKE CASES            12989.0
2  COLOUR GLASS T-LIGHT HOLDER HANGING             7785.0
3   PACK OF 60 PINK PAISLEY CAKE CASES             7672.0
4              LUNCH BAG RED RETROSPOT             7326.0
5   WHITE HANGING HEART T-LIGHT HOLDER             7251.0
6          60 TEATIME FAIRY CAKE CASES             7227.0
7        ASSORTED COLOUR BIRD ORNAMENT             7198.0
8               JAM MAKING SET PRINTED             6894.0
9      VICTORIAN GLASS HANGING T-LIGHT             6676.0

8. What is Average order value

In [33]:
query = """
SELECT
    ROUND(SUM(SalesAmount) / COUNT(DISTINCT InvoiceNo), 2) AS AverageOrderValue
FROM online_retail;
"""

pd.read_sql_query(query, conn)

   AverageOrderValue
0             268.39

9. Which customers have placed the most orders

In [34]:
query = """
SELECT
    CustomerID,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders
FROM online_retail
WHERE CustomerID IS NOT NULL
GROUP BY CustomerID
ORDER BY TotalOrders DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

   CustomerID  TotalOrders
0     12748.0          130
1     14911.0          104
2     17841.0           81
3     14606.0           70
4     15311.0           65
5     13089.0           58
6     12971.0           58
7     14527.0           40
8     15039.0           37
9     17850.0           34

10. Which products are low in quantity but generates high revenue

In [35]:
query = """
SELECT
    Description,
    SUM(Quantity) AS TotalQuantity,
    ROUND(SUM(SalesAmount), 2) AS TotalRevenue,
    ROUND(SUM(SalesAmount) / SUM(Quantity), 2) AS RevenuePerUnit
FROM online_retail
GROUP BY Description
HAVING SUM(Quantity) > 0
ORDER BY RevenuePerUnit DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

,Description,TotalQuantity,TotalRevenue,RevenuePerUnit
0,3 TIER SWEETHEART GARDEN SHELF,34.0,1219.30,35.86
1,Dotcomgiftshop Gift Voucher £40.00,3.0,100.70,33.57
2,IVORY EMBROIDERED QUILT,2.0,66.58,33.29
3,SAMPLES,1.0,30.00,30.00
4,WOOD AND GLASS MEDICINE CABINET,7.0,209.65,29.95
5,SILVER ROCCOCO CHANDELIER,1.0,29.95,29.95
6,CAPIZ CHANDELIER,1.0,29.95,29.95
7,Dotcomgiftshop Gift Voucher £30.00,7.0,175.53,25.08
8,VINTAGE WOODEN BAR STOOL,2.0,49.95,24.98
9,"RUSTIC WOODEN CABINET, GLASS DOORS",1.0,24.95,24.95

Connecting Sqlite using Sqlalchemy

In [36]:
from sqlalchemy import create_engine

engine = create_engine("sqlite:////content/online_retail.db")

print("SQLAlchemy connection created successfully!")

SQLAlchemy connection created successfully!

Read results directly into pandas

In [37]:
query = """
SELECT
    Country,
    ROUND(SUM(SalesAmount), 2) AS TotalSales
FROM online_retail
GROUP BY Country
ORDER BY TotalSales DESC
LIMIT 10;
"""

result = pd.read_sql(query, engine)

result

           Country  TotalSales
0   United Kingdom  2777079.64
1          Germany    84712.54
2           France    73956.61
3             EIRE    66950.33
4            Spain    20741.18
5          Belgium    20049.19
6      Switzerland    16364.89
7         Portugal    11019.69
8           Norway     8326.49
9  Channel Islands     7876.43

In [38]:
query = """
SELECT
    CustomerID,
    ROUND(SUM(SalesAmount), 2) AS TotalRevenue,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders
FROM online_retail
WHERE CustomerID IS NOT NULL
GROUP BY CustomerID
ORDER BY TotalRevenue DESC
LIMIT 10;
"""

top_customers = pd.read_sql(query, engine)

top_customers

   CustomerID  TotalRevenue  TotalOrders
0     14911.0      43958.74          104
1     13089.0      21071.96           58
2     17841.0      19709.80           81
3     14298.0      19615.81           34
4     15039.0      11907.95           37
5     13081.0      11412.60            8
6     14156.0      11237.27           28
7     12748.0      10716.07          130
8     17735.0      10103.33           16
9     15311.0       9481.58           65

Calculating and displaying KPI Value

In [39]:
query = """
SELECT
    COUNT(DISTINCT InvoiceNo) AS TotalOrders,
    ROUND(SUM(SalesAmount), 2) AS TotalRevenue,
    COUNT(DISTINCT StockCode) AS UniqueProducts,
    COUNT(DISTINCT CustomerID) AS UniqueCustomers
FROM online_retail;
"""

kpi = pd.read_sql(query, engine)

kpi

print("Total Orders:", kpi.loc[0, "TotalOrders"])
print("Total Revenue:", kpi.loc[0, "TotalRevenue"])
print("Unique Products:", kpi.loc[0, "UniqueProducts"])
print("Unique Customers:", kpi.loc[0, "UniqueCustomers"])

Total Orders: 11764
Total Revenue: 3157350.82
Unique Products: 3650
Unique Customers: 3238

In [40]:
%%writefile sql_utils.py

import sqlite3
import pandas as pd


def connect_database(db_path):
    """Create and return a SQLite database connection."""
    return sqlite3.connect(db_path)


def run_query(connection, query):
    """Execute a SQL query and return the result as a DataFrame."""
    return pd.read_sql_query(query, connection)


def get_table_info(connection, table_name):
    """Return information about the columns in a SQLite table."""
    query = f"PRAGMA table_info({table_name});"
    return pd.read_sql_query(query, connection)


if __name__ == "__main__":
    print("SQL utility module loaded successfully.")

Writing sql_utils.py

In [41]:
from sql_utils import connect_database, run_query, get_table_info

test_conn = connect_database("/content/online_retail.db")

query = """
SELECT
    Country,
    ROUND(SUM(SalesAmount), 2) AS TotalSales
FROM online_retail
GROUP BY Country
ORDER BY TotalSales DESC
LIMIT 10;
"""

result = run_query(test_conn, query)

result

           Country  TotalSales
0   United Kingdom  2777079.64
1          Germany    84712.54
2           France    73956.61
3             EIRE    66950.33
4            Spain    20741.18
5          Belgium    20049.19
6      Switzerland    16364.89
7         Portugal    11019.69
8           Norway     8326.49
9  Channel Islands     7876.43

In [42]:
table_info = get_table_info(test_conn, "online_retail")

table_info

   cid         name     type  notnull dflt_value  pk
0    0    InvoiceNo  INTEGER        0       None   0
1    1    StockCode     TEXT        0       None   0
2    2  Description     TEXT        0       None   0
3    3     Quantity     REAL        0       None   0
4    4  InvoiceDate     TEXT        0       None   0
5    5    UnitPrice     REAL        0       None   0
6    6   CustomerID     REAL        0       None   0
7    7      Country     TEXT        0       None   0
8    8  SalesAmount     REAL        0       None   0

In [43]:
%%writefile Task_2_Queries.sql

-- ============================================================
-- ApexPlanet Data Analytics Internship
-- Task 2: SQL for Data Extraction
-- Dataset: E-Commerce Sales
-- ============================================================


-- ============================================================
-- SQL FUNDAMENTALS
-- ============================================================

-- 1. Select specific columns
SELECT InvoiceNo, Description, Quantity, UnitPrice, SalesAmount
FROM online_retail
LIMIT 10;


-- 2. Filter transactions
SELECT InvoiceNo, Description, Quantity, SalesAmount
FROM online_retail
WHERE Quantity > 100
LIMIT 20;


-- 3. Sort transactions by sales
SELECT InvoiceNo, Description, Quantity, SalesAmount
FROM online_retail
ORDER BY SalesAmount DESC
LIMIT 10;


-- 4. Find unique countries
SELECT DISTINCT Country
FROM online_retail
ORDER BY Country;


-- 5. Count total transactions
SELECT COUNT(*) AS TotalTransactions
FROM online_retail;


-- 6. Total sales by country
SELECT
    Country,
    SUM(SalesAmount) AS TotalSales
FROM online_retail
GROUP BY Country
ORDER BY TotalSales DESC;


-- 7. Countries with sales greater than £10,000
SELECT
    Country,
    SUM(SalesAmount) AS TotalSales
FROM online_retail
GROUP BY Country
HAVING SUM(SalesAmount) > 10000
ORDER BY TotalSales DESC;


-- 8. Overall sales statistics
SELECT
    COUNT(DISTINCT InvoiceNo) AS TotalOrders,
    COUNT(DISTINCT StockCode) AS UniqueProducts,
    SUM(Quantity) AS TotalQuantity,
    SUM(SalesAmount) AS TotalSales,
    AVG(SalesAmount) AS AverageTransactionValue,
    MIN(SalesAmount) AS MinimumSale,
    MAX(SalesAmount) AS MaximumSale
FROM online_retail;


-- 9. Top 10 products by sales
SELECT
    Description,
    SUM(Quantity) AS TotalQuantity,
    SUM(SalesAmount) AS TotalSales
FROM online_retail
GROUP BY Description
ORDER BY TotalSales DESC
LIMIT 10;


-- 10. Monthly sales
SELECT
    strftime('%Y-%m', InvoiceDate) AS YearMonth,
    SUM(SalesAmount) AS TotalSales
FROM online_retail
GROUP BY YearMonth
ORDER BY YearMonth;


-- ============================================================
-- ADVANCED SQL
-- ============================================================

-- 11. Subquery: transactions above average sales
SELECT
    InvoiceNo,
    Description,
    Quantity,
    SalesAmount
FROM online_retail
WHERE SalesAmount > (
    SELECT AVG(SalesAmount)
    FROM online_retail
)
ORDER BY SalesAmount DESC
LIMIT 20;


-- 12. CTE: country sales above £10,000
WITH CountrySales AS (
    SELECT
        Country,
        SUM(SalesAmount) AS TotalSales
    FROM online_retail
    GROUP BY Country
)
SELECT
    Country,
    TotalSales
FROM CountrySales
WHERE TotalSales > 10000
ORDER BY TotalSales DESC;


-- 13. Window function: country sales ranking
WITH CountrySales AS (
    SELECT
        Country,
        SUM(SalesAmount) AS TotalSales
    FROM online_retail
    GROUP BY Country
)
SELECT
    Country,
    TotalSales,
    RANK() OVER (ORDER BY TotalSales DESC) AS SalesRank
FROM CountrySales
ORDER BY SalesRank;


-- 14. Window function: product sales ranking
WITH ProductSales AS (
    SELECT
        Description,
        SUM(SalesAmount) AS TotalSales
    FROM online_retail
    GROUP BY Description
)
SELECT
    Description,
    TotalSales,
    RANK() OVER (ORDER BY TotalSales DESC) AS SalesRank
FROM ProductSales
ORDER BY SalesRank
LIMIT 20;


-- 15. Create country sales view
CREATE VIEW IF NOT EXISTS country_sales AS
SELECT
    Country,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders,
    SUM(Quantity) AS TotalQuantity,
    SUM(SalesAmount) AS TotalSales
FROM online_retail
GROUP BY Country;


-- View results
SELECT *
FROM country_sales
ORDER BY TotalSales DESC;


-- ============================================================
-- 10 BUSINESS QUESTIONS
-- ============================================================

-- Business Question 1:
-- What is the total revenue?
SELECT
    ROUND(SUM(SalesAmount), 2) AS TotalRevenue
FROM online_retail;


-- Business Question 2:
-- Which are the top 10 products by revenue?
SELECT
    Description,
    ROUND(SUM(SalesAmount), 2) AS TotalRevenue
FROM online_retail
GROUP BY Description
ORDER BY TotalRevenue DESC
LIMIT 10;


-- Business Question 3:
-- Which countries generate the most revenue?
SELECT
    Country,
    ROUND(SUM(SalesAmount), 2) AS TotalRevenue
FROM online_retail
GROUP BY Country
ORDER BY TotalRevenue DESC
LIMIT 10;


-- Business Question 4:
-- Which countries have the most orders?
SELECT
    Country,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders
FROM online_retail
GROUP BY Country
ORDER BY TotalOrders DESC
LIMIT 10;


-- Business Question 5:
-- What are the top 10 customers by revenue?
SELECT
    CustomerID,
    ROUND(SUM(SalesAmount), 2) AS TotalRevenue
FROM online_retail
WHERE CustomerID IS NOT NULL
GROUP BY CustomerID
ORDER BY TotalRevenue DESC
LIMIT 10;


-- Business Question 6:
-- What is the monthly revenue trend?
SELECT
    strftime('%Y-%m', InvoiceDate) AS YearMonth,
    ROUND(SUM(SalesAmount), 2) AS MonthlyRevenue
FROM online_retail
GROUP BY YearMonth
ORDER BY YearMonth;


-- Business Question 7:
-- Which products have the highest quantity sold?
SELECT
    Description,
    SUM(Quantity) AS TotalQuantitySold
FROM online_retail
GROUP BY Description
ORDER BY TotalQuantitySold DESC
LIMIT 10;


-- Business Question 8:
-- What is the average order value?
SELECT
    ROUND(
        SUM(SalesAmount) / COUNT(DISTINCT InvoiceNo),
        2
    ) AS AverageOrderValue
FROM online_retail;


-- Business Question 9:
-- Which customers have placed the most orders?
SELECT
    CustomerID,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders
FROM online_retail
WHERE CustomerID IS NOT NULL
GROUP BY CustomerID
ORDER BY TotalOrders DESC
LIMIT 10;


-- Business Question 10:
-- Which products generate high revenue per unit?
SELECT
    Description,
    SUM(Quantity) AS TotalQuantity,
    ROUND(SUM(SalesAmount), 2) AS TotalRevenue,
    ROUND(SUM(SalesAmount) / SUM(Quantity), 2) AS RevenuePerUnit
FROM online_retail
GROUP BY Description
HAVING SUM(Quantity) > 0
ORDER BY RevenuePerUnit DESC
LIMIT 10;

Writing Task_2_Queries.sql